# fly.toml app configuration file generated for canchas-back on 2024-11-11T20:54:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'canchas-back'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
